## Práctica 1

1) Creación de Arrays

In [25]:
import numpy as np

In [15]:
#(a) Crea un array a con los números del 0 al 19.
a = np.arange(20)
print(a)

#(b) Crea un array b de tamaño 10 con números aleatorios entre 0 y 1.
np.random.seed(2022) #Replicabilidad
b = np.random.randint(0,2,10)
print(b)

#(c) Crea una matriz c de 3x3 con todos sus elementos iguales a 5.
c = np.array([5,5,5,5,5,5,5,5,5]).reshape(3,3)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 0 1 0 1 1 0 1 0 0]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


2) Indexación y slicing

In [18]:
x = np.arange(10, 30)
print(x)

#(a) Muestra los elementos del índice 3 al 8
print(x[3:9]) #indicamos hasta nueve porque muestra hasta el índice anterior a 8 inclusive

print("-"*10)

#(b) Muestra los elementos pares del array.

#Para ser pares modul: tiene que ser 0
modul = x%2
print(modul)

#Muestra los que son pares
print(x[modul==0])

print("-"*10)

#(c) Cambia el valor del último elemento a 100.

#Longitud de x y Ultima posición
last_pos = len(x)-1

#Modificar último valor
x[last_pos]=100
print(x)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[13 14 15 16 17 18]
----------
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
[10 12 14 16 18 20 22 24 26 28]
----------
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28 100]


3) Operaciones vectorizadas

In [29]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

#a = np.vectorize(a)
#b = np.vectorize(b)

In [48]:
print(a.shape)
print(b.shape)

#(a) Calcula:

#a+b
print(a+b)

#a*b
print(a*b)

#b / a
print(b/a)

#(b) Eleva cada elemento de a al cuadrado usando una función vectorizada:

#(1)Función
def fun(x):
    return x**2

#(2)Vectorizar Función
vfun = np.vectorize(fun) 

print(vfun(a))


(5,)
(5,)
[11 22 33 44 55]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[ 1  4  9 16 25]


4) Estadísticas básicas

In [104]:
#Crea un array aleatorio de 20 valores enteros entre 1 y 100:
arr = np.random.randint(1, 101, size=20)

In [106]:
print(arr)
print("-"*10)

#Calcula y muestra:

#(a) La media.
print(np.mean(arr))
print("-"*10)

#(b) La desviación estándar.
print(np.std(arr))
print("-"*10)

#(c) El valor máximo y su posición (índice)
print(np.max(arr))
print(np.argmax(arr))


[25 17 54 42 34 28 12 20 95 76 49 20 39 73 15 94 17 91 12 95]
----------
45.4
----------
30.088868373536414
----------
95
8


5) Manipulación de matrices

In [146]:
#(a) Crea una matriz M de tamaño 4x4 con números del 1 al 16.

M = np.arange(1,17).reshape(4,4)
print(M)
print("-"*10)

#(b) Muestra:

#La primera fila.
print(M[0])
print("-"*10)

#La última columna.
num_cols = M.shape[1]

print(M[:,M.shape[1]-1])
print("-"*10)

#La submatriz central de 2x2.
print(M[1:3,1:3])
print("-"*10)


#(c) Calcula la suma de cada fila y de cada columna

print(np.sum(M, axis=0)) #Sumar por columnas
print(np.sum(M, axis=1)) #Sumar por filas


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
----------
[1 2 3 4]
----------
[ 4  8 12 16]
----------
[[ 6  7]
 [10 11]]
----------
[28 32 36 40]
[10 26 42 58]


6) Aplicación práctica

In [166]:
#Supón que tienes un array que representa las temperaturas diarias (°C) de una ciudad durante una semana:
temps = np.array([18, 20, 22, 21, 19, 17, 16])

#(a) Calcula la temperatura media semanal.
media = np.mean(temps)
print(media)
print("-"*10)

#(b) Muestra qué días estuvieron por encima del promedio.
print(temps[temps>media])
print("-"*10)

#(c) Convierte todas las temperaturas a °F usando la fórmula:
Faren = temps*(9/5) + 32
print(Faren)
print("-"*10)

#(d) Agrega una nueva temperatura (día 8 = 23°C) al array original.

#(1) Saber longitud del array
longit = len(temps)
print(longit)

#(2) Añadir al final 
np.append(temps, 23)    # Usamos append

19.0
----------
[20 22 21]
----------
[64.4 68.  71.6 69.8 66.2 62.6 60.8]
----------
7


array([18, 20, 22, 21, 19, 17, 16, 23])

In [ ]:
7) Operaciones de conjuntos

Dadas los ficheros .csv datos 1.csv y datos 2.csv (disponibles en la página de la
asignatura) que contienen respectivas arrays

In [54]:
import numpy as np

In [56]:
data1 = np.loadtxt("data/datos_1.csv", delimiter=",", usecols=(1,))
print(data1)
print(data1.shape)
print("-"*10)

data2 = np.loadtxt("data/datos_2.csv", delimiter=",", usecols=(1,), skiprows=1, encoding="latin-1")
print(data2)
print(data2.shape)

[16. 14. 31. 59. 90. 62.]
(6,)
----------
[44. 59. 25. 60. 16.]
(5,)


In [58]:
import numpy as np

with open("data/datos_1.csv", encoding="latin-1") as f:
    rows = [line.strip().strip('"').split(',') for line in f if line.strip()]

data1 = np.array(rows, dtype=float)  # matriz 2D
print(data1)

with open("data/datos_2.csv", encoding="latin-1") as f:
    rows = [line.strip().strip('"').split(',') for line in f if line.strip()]

data2 = np.array(rows, dtype=float)  # matriz 2D
print(data2)

[[ 42.  16.   8.  95.  59.  57.  91.  75.   5.  45.]
 [ 52.  14.  90.   2.   7.  79.  57.   1.  43.  27.]
 [ 36.  31.  46.  79.  25.  61. 100.  63.  36.  24.]
 [ 83.  59.  33.  95.  94.  76.  91.  33.  55.  62.]
 [ 60.  90.  67.  66.  34.  71.  93.  20.  77.  51.]
 [ 24.  62.  72.  17.  78.  93.  52.  24.  86.  10.]]
[[ 38.   5.   6.  57.  67.  52.  77.  99.  80.  74.]
 [ 49.  44.  20.  97.   3.  82.  46.  81. 100.  47.]
 [ 83.  59.  33.  95.  94.  76.  91.  33.  55.  62.]
 [ 34.  25.  85.  61.  65.  73.  59.  22.  45.  90.]
 [ 14.  60.  46.  85.  52.  93.  38.  89.  79.  10.]
 [ 42.  16.   8.  95.  59.  57.  91.  75.   5.  45.]]


In [60]:
#(a) El conjunto de variables estadísticas básicas:

# Media.
print("Media de Datos 1: ", np.mean(data1))
print("Media de Datos 2: ", np.mean(data2))
print("-"*10)

# Mediana.
print("Mediana de Datos 1: ", np.median(data1))
print("Mediana de Datos 2: ", np.median(data2))
print("-"*10)

# Valor máximo y mínimo.
print("Max de Datos 1: ", np.max(data1))
print("Max de Datos 2: ", np.max(data2))
print("Min de Datos 1: ", np.min(data1))
print("Min de Datos 2: ", np.min(data2))
print("-"*10)

# Número de elementos presentes en cada fichero.
print("Numero de elementos en Datos 1: ", data1.size)
print("Numero de elementos en Datos 2: ", data2.size)

Media de Datos 1:  53.233333333333334
Media de Datos 2:  57.05
----------
Mediana de Datos 1:  57.0
Mediana de Datos 2:  59.0
----------
Max de Datos 1:  100.0
Max de Datos 2:  100.0
Min de Datos 1:  1.0
Min de Datos 2:  3.0
----------
Numero de elementos en Datos 1:  60
Numero de elementos en Datos 2:  60


In [62]:
#Añadir filas
data3 = np.concatenate((data1,data2), axis=0)
data3

# Media.
print("Media de Datos 3: ", np.mean(data3))
print("-"*10)

# Mediana.
print("Mediana de Datos 3: ", np.median(data3))
print("-"*10)

# Valor máximo y mínimo.
print("Max de Datos 3: ", np.max(data3))
print("Min de Datos 3: ", np.min(data3))
print("-"*10)

# Número de elementos presentes en cada fichero.
print("Numero de elementos en Datos 3: ", data3.size)

Media de Datos 3:  55.141666666666666
----------
Mediana de Datos 3:  58.0
----------
Max de Datos 3:  100.0
Min de Datos 3:  1.0
----------
Numero de elementos en Datos 3:  120


In [64]:
#(b) La intersección de los elementos de la primera fila de los dos arrays.
print(np.intersect1d(data1[0], data2[0]))

#(c) La unión de los elementos de las primeras filas de los dos arrays (sin duplicados).
print(np.union1d(data1[0], data2[0]))



[ 5. 57.]
[ 5.  6.  8. 16. 38. 42. 45. 52. 57. 59. 67. 74. 75. 77. 80. 91. 95. 99.]


In [116]:
#ALTERNATIVA 1
import numpy as np
a = np.ascontiguousarray(data1)
b = np.ascontiguousarray(data2)

dt = np.dtype([('f'+str(i), a.dtype) for i in range(a.shape[1])])

rows = np.intersect1d(a.view(dt).ravel(), b.view(dt).ravel())
rows = rows.view(a.dtype).reshape(-1, a.shape[1])
rows

array([[42., 16.,  8., 95., 59., 57., 91., 75.,  5., 45.],
       [83., 59., 33., 95., 94., 76., 91., 33., 55., 62.]])

In [114]:
#ALTERNATIVA 2
a, b = map(np.ascontiguousarray, (data1, data2))          # 2D, mismo nº de columnas
dt = np.dtype((np.void, a.dtype.itemsize * a.shape[1]))   # “fila” como bloque de bytes
rows = np.intersect1d(a.view(dt).ravel(), b.view(dt).ravel()) \
           .view(a.dtype).reshape(-1, a.shape[1])

print(rows)


[[42. 16.  8. 95. 59. 57. 91. 75.  5. 45.]
 [83. 59. 33. 95. 94. 76. 91. 33. 55. 62.]]


In [112]:
#(d) Filas repetidas en ambos ficheros (de uno al otro)
rows = np.intersect1d(data1, data2, axis=0)
print(rows)

TypeError: intersect1d() got an unexpected keyword argument 'axis'

In [11]:
#(d) Filas repetidas en ambos ficheros (entiendo que se repiten, ya sea en uno como en otro)

#(1) Filas unicas y su frecuencia
unique_3, freq_3 = np.unique(data3, axis=0, return_counts=True)

#(2) Filas Unicas
print(unique_3)

#(3) Veces que se repite cada una
print(freq_3)
print("-"*10)

#(4) Mostrar filas que cumplen esas condiciones: Filas de posiciones donde la frecuencia es mayor a 1
print(unique_3[np.argwhere(freq_3>1)])

[[ 14.  60.  46.  85.  52.  93.  38.  89.  79.  10.]
 [ 24.  62.  72.  17.  78.  93.  52.  24.  86.  10.]
 [ 34.  25.  85.  61.  65.  73.  59.  22.  45.  90.]
 [ 36.  31.  46.  79.  25.  61. 100.  63.  36.  24.]
 [ 38.   5.   6.  57.  67.  52.  77.  99.  80.  74.]
 [ 42.  16.   8.  95.  59.  57.  91.  75.   5.  45.]
 [ 49.  44.  20.  97.   3.  82.  46.  81. 100.  47.]
 [ 52.  14.  90.   2.   7.  79.  57.   1.  43.  27.]
 [ 60.  90.  67.  66.  34.  71.  93.  20.  77.  51.]
 [ 83.  59.  33.  95.  94.  76.  91.  33.  55.  62.]]
[1 1 1 1 1 2 1 1 1 2]
----------
[[[42. 16.  8. 95. 59. 57. 91. 75.  5. 45.]]

 [[83. 59. 33. 95. 94. 76. 91. 33. 55. 62.]]]


In [382]:
# 1. Convierte las filas de cada array a un conjunto de tuplas

# Esto permite que Python trate cada fila como un elemento único e inmutable
set1 = set(map(tuple, data1))
set2 = set(map(tuple, data2))

# 2. Encuentra la intersección de los dos conjuntos

# El resultado serán las filas comunes (como tuplas)
interseccion_tuplas = set1.intersection(set2)


# 3. Convierte las tuplas resultantes de nuevo a un array de NumPy
filas_comunes = np.array(list(interseccion_tuplas))

print("Filas Comunes (Intersección):")
print(filas_comunes)

Filas Comunes (Intersección):
[[42. 16.  8. 95. 59. 57. 91. 75.  5. 45.]
 [83. 59. 33. 95. 94. 76. 91. 33. 55. 62.]]


In [270]:
# https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html
data = np.loadtxt("data/GALIBOS TUNELES MADRID.csv", delimiter=";", usecols = 1, skiprows=1, converters={1: lambda s:float(str(s).replace(",","."))},
                 encoding = "latin-1")
print(data)
print(data.shape)

[2.95 4.   4.   4.   4.   4.   3.9  3.5  3.5  3.5  4.3  4.5  3.   3.
 2.95 4.   4.5  3.   4.   3.   4.   3.   3.   4.   3.   2.95 4.   4.
 4.   3.   2.95 2.85 2.85 3.   3.   3.   2.85 3.   3.   3.   3.   3.
 3.   2.85 4.   4.   3.   2.4  4.   4.   4.   4.3  3.5  2.7  2.95 2.95
 2.95 2.95 1.95 2.4 ]
(60,)


In [274]:
# https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html
data = np.loadtxt("data/datos_1.csv", delimiter=";", usecols = 1, skiprows=1, converters={1: lambda s:float(str(s).replace(",","."))},
                 encoding = "latin-1")
print(data)
print(data.shape)

ValueError: invalid column index 1 at row 1 with 1 columns

In [330]:
# https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html
data = np.loadtxt("data/data_1.csv", delimiter=";", usecols = 1, skiprows=1, converters={1: lambda s:float(str(s.decode()).replace(",","."))})
print(data)
print(data.shape)

FileNotFoundError: data/data_1.csv not found.

In [278]:
import numpy as np

with open("data/datos_1.csv", encoding="latin-1") as f:
    rows = [line.strip().strip('"').split(',') for line in f if line.strip()]

arr = np.array(rows, dtype=float)  # matriz 2D
col2 = arr[:, 1]                   # ejemplo: segunda “columna”


In [280]:
arr

array([[ 42.,  16.,   8.,  95.,  59.,  57.,  91.,  75.,   5.,  45.],
       [ 52.,  14.,  90.,   2.,   7.,  79.,  57.,   1.,  43.,  27.],
       [ 36.,  31.,  46.,  79.,  25.,  61., 100.,  63.,  36.,  24.],
       [ 83.,  59.,  33.,  95.,  94.,  76.,  91.,  33.,  55.,  62.],
       [ 60.,  90.,  67.,  66.,  34.,  71.,  93.,  20.,  77.,  51.],
       [ 24.,  62.,  72.,  17.,  78.,  93.,  52.,  24.,  86.,  10.]])